### ISSUE TITLE
PHP Time zone as a variable?

### ISSUE THREAD

**Issue by james2doyle** [invokemedia/ansible-laravel-settler#2]
Usually this is set via the app that is running. But right now the server is hard coded at UTC

**Comment by james2doyle** [comment]
Maybe it should double up on the system timezone? https://github.com/invokemedia/ansible-laravel-settler/blob/master/defaults/main.yml#L14

**Comment by smiller171** [comment]
It looks like all you have to do is run the role with the `settler_timezone_file` var set to the time zone file you want.

**Comment by james2doyle** [comment]
Yeah, I was thinking that. But there is an argument where the timezone of the server should be agnostic of the location it is being used. Then the timezone is set per app, or in an environment variable for the app

**Comment by smiller171** [comment]
@james2doyle that's only relevant if you are running multiple applications per server, which isn't advised unless you are using Docker. Use fewer smaller servers instead.

**Comment by james2doyle** [comment]
@smiller171 its also relevant if you are using timestamps or showing time/dates. We have this problem right now. We have an order that is timestamped. It is showing up as in the future because the server is UTC and the local timezone is PST

**Comment by smiller171** [comment]
@james2doyle that sounds like you are agreeing with me as a reason to set the server time to PST

**Comment by james2doyle** [comment]
@smiller171 but setting it to PST also means that anyone _not_ PST will have the same issue non-PST people had before. If the expectation was that the server is _only used_ in PST locations, then this would be a no-brainer
